# -*- coding: utf-8 -*-
"""mathplot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGhS250yxg2RA6T0UaXFdjQLNa4QzC5M
"""

import numpy as np
import matplotlib.pyplot as pt
import pandas as pd

pt.plot([1,2,3,4],[5,6,7,8],color="purple",linestyle="dashdot",linewidth=6)

grades=np.array([6,7,8,9])
percentage=np.array([85,95,87,92])
pt.plot(grades,percentage)
pt.xlabel("grades")
pt.ylabel("percentage")
pt.title("report")

y=np.array([3,8,1,10])
pt.plot(y,marker="o")

x=[6,7,9,4,5]
y=[1,2,4,6,7]
pt.scatter(x,y,marker=",")

x=["a","b","c","d"]
y=[3,8,1,10]
pt.barh(x,y,color="hotpink",)

davin=[25,25,15,65]
label=["Davin","Diego","Darend","Bob"]
diego=[0.2,0,0,0]
u=["purple","hotpink","yellow","blue"]
pt.pie(davin,labels=label,startangle=90,explode=diego,shadow=True,colors=u)
pt.legend(title="names")
pt.show()

from google.colab import drive
drive.mount("\contents\drive")

match=pd.read_csv("/content/contentsdrive/MyDrive/Generic Folder/matches (1).csv")

match.head()

match.shape

match['player_of_match'].value_counts()[0:5]

match['toss_winner'].value_counts()

pt.bar(match['player_of_match'].value_counts()[0:5].keys(),match['player_of_match'].value_counts()[0:5])

pt.barh(match['toss_winner'].value_counts().keys(),match['toss_winner'].value_counts())

f=match[match['win_by_runs']!=0]
f

pt.hist(f['win_by_runs'])
pt.show()

f['winner'].value_counts()

pt.bar(f['winner'].value_counts()[0:3].keys(),f['winner'].value_counts()[0:3])

pt.figure(figsize=(15,15))
pt.pie(f['winner'].value_counts(),labels=f['winner'].value_counts().keys(),autopct="%0.01f%%")
pt.show()

i=match[match['win_by_wickets']!=0]
i

pt.hist(i["win_by_wickets"])
pt.show

pt.figure(figsize=(20,20))
pt.pie(i['winner'].value_counts(),labels=i['winner'].value_counts().keys(),autopct="%0.01f%%")
pt.show

"""create a graph with movies and purchases"""

movies=pd.read_csv("/content/contentsdrive/MyDrive/Generic Folder/Movie_data.csv")

movies.head()

pt.bar(movies['Year'].value_counts()[0:10].keys(),movies['Year'].value_counts()[0:10])
pt.show